// GENERATED by tools/convert_3d_models.py - DO NOT EDIT BY HAND.
// Local-space (pivot-space) bounding boxes of the ORIGINAL castle-piece
// meshes, measured from the w3d-extracted geometry. Pivots are not bbox
// centers (e.g. wallA spans x 0..5): the layout strings place pieces by
// pivot, so colliders are derived from these boxes at runtime (world.ts).

export interface ModelBBox {
  bboxMin: [number, number, number];
  bboxMax: [number, number, number];
}

export const PIECE_BBOX: Record<string, ModelBBox> = {
  wallA: {
    bboxMin: [0.058, -14.89, 0.481],
    bboxMax: [4.942, 14.89, 15.033],
  },
  wallB: {
    bboxMin: [-4.929, -14.941, 0.483],
    bboxMax: [4.929, 14.941, 15.099],
  },
  towerA: {
    bboxMin: [-4.909, -4.909, 0.554],
    bboxMax: [9.909, 9.909, 14.896],
  },
  wallTopA: {
    bboxMin: [0.077, -14.89, 0.496],
    bboxMax: [4.942, 14.918, 15.049],
  },
  wallTopB: {
    bboxMin: [-4.96, -14.897, 0.458],
    bboxMax: [4.96, 14.897, 15.01],
  },
  towerTopA: {
    bboxMin: [-4.909, -4.909, 0.545],
    bboxMax: [9.909, 9.909, 14.984],
  },
  drawbridgeA: {
    bboxMin: [0.086, -9.887, 0.543],
    bboxMax: [4.914, 9.887, 35.213],
  },
  archA: {
    bboxMin: [-4.936, -14.89, 0.546],
    bboxMax: [4.936, 14.89, 15.595],
  },
  towerTopB: {
    bboxMin: [-14.94, -14.964, 0.584],
    bboxMax: [14.94, 14.964, 14.962],
  },
  wallPieceA: {
    bboxMin: [-4.82, 0.07, 0.502],
    bboxMax: [4.82, 4.93, 15.156],
  },
  supportA: {
    bboxMin: [-4.858, -4.914, 0.51],
    bboxMax: [9.858, 4.914, 15.403],
  },
  supportB: {
    bboxMin: [-9.862, 0.07, 0.519],
    bboxMax: [9.862, 4.93, 25.519],
  },
  cannonA: {
    bboxMin: [-4.939, 0.101, 0.471],
    bboxMax: [4.939, 4.899, 6.565],
  },
  cannonB: {
    bboxMin: [-9.923, -4.834, 0.494],
    bboxMax: [9.923, 4.834, 10.419],
  },
  flagPoleC: {
    bboxMin: [0.168, -2.038, 1.379],
    bboxMax: [4.832, 4.832, 10.572],
  },
};

/** True mesh radius of the ball master; gameClass scales it 3.4x (6x for cannonB). */
export const BALL_MESH_RADIUS = 1.768;

export interface MaterialSpec {
  map?: string;
  color?: string;
  specular?: boolean;
  opacity?: number;
  alphaTest?: number;
  doubleSide?: boolean;
  unlit?: boolean;
}

export const MODEL_MATERIALS: Record<string, MaterialSpec> = {
  shaderbrick: {
    map: "shaderbrick",
  },
  shadercannon1: {
    map: "shadercannon1",
  },
  shadercannon2: {
    map: "shadercannon2",
  },
  shaderdrawbridge: {
    map: "shaderdrawbridge",
  },
  shaderGround: {
    map: "shaderGround",
  },
  blinn4: {
    map: "skydome",
  },
  treeTexture: {
    map: "treeTexture",
    alphaTest: 0.5,
    doubleSide: true,
    unlit: true,
  },
  shadergold: {
    color: "#BDB400",
    specular: true,
  },
  shaderball: {
    color: "#000000",
    specular: true,
  },
  lambert7: {
    color: "#000000",
    opacity: 0.68,
    doubleSide: true,
    unlit: true,
  },
};
